# 워크플로우의 이름입니다.
name: Create Release and Upload DMG

# 'v'로 시작하는 태그가 푸시될 때 실행됩니다.
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Node.js 24 -> 20으로 수정 (안정성)

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      # 릴리즈 생성 단계에 ID를 부여하여, 출력값을 다음 단계에서 사용할 수 있게 합니다.
      - name: Create Release and Upload Asset
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dmg

      # 다른 워크플로우를 깨우는 '신호'를 보냅니다.
      - name: Dispatch Tap Update Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          # 신호를 보낼 때 사용자님의 권한(PAT)이 반드시 필요합니다.
          token: ${{ secrets.TAP_REPO_TOKEN }}
          # 이 신호의 이름입니다.
          event-type: new-release-created
          # --- 여기가 가장 중요한 수정 부분 ---
          # 신호를 보낼 때, 필요한 정보들을 'client-payload'에 담아서 보냅니다.
          client-payload: >-
            {
              "version": "${{ github.ref_name }}",
              "download_url": "${{ fromJson(steps.create_release.outputs.assets)[0].browser_download_url }}"
            }
