name: Update Homebrew Tap

# "new-release-created" 라는 신호를 받았을 때 실행
on:
  repository_dispatch:
    types: [${{ vars.EVENT_TYPE_NAME }}]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      # 1. Tap 저장소 체크아웃
      - name: Check out homebrew-gemini-app
        uses: actions/checkout@v4
        with:
          repository: ChoiSeungWoo98/homebrew-gemini-app
          token: ${{ secrets.TAP_REPO_TOKEN }}

      # 2. 변수 준비
      - name: Prepare update variables
        run: |
          curl -L -o asset.dmg "${{ github.event.client_payload.download_url }}"
          echo "NEW_SHA256=$(shasum -a 256 asset.dmg | awk '{print $1}')" >> $GITHUB_ENV
          echo "NEW_VERSION=$(echo "${{ github.event.client_payload.version }}" | sed 's/^v//')" >> $GITHUB_ENV

      # 3. Cask 파일의 version 정보 업데이트
      - name: Update version in Cask file
        uses: jamesives/find-replace-action@v4
        with:
          find: 'version ".*"'
          replace: 'version "${{ env.NEW_VERSION }}"'
          include: 'Casks/my-gemini-app.rb'

      # 4. Cask 파일의 sha256 정보 업데이트
      - name: Update sha256 in Cask file
        uses: jamesives/find-replace-action@v4
        with:
          find: 'sha256 ".*"'
          replace: 'sha256 "${{ env.NEW_SHA256 }}"'
          include: 'Casks/my-gemini-app.rb'

      # 5. Cask 파일의 다운로드 URL 정보 업데이트
      - name: Update url in Cask file
        uses: jamesives/find-replace-action@v4
        with:
          find: 'url ".*"'
          replace: 'url "${{ github.event.client_payload.download_url }}"'
          include: 'Casks/my-gemini-app.rb'

      # 6. 변경된 파일을 커밋하고 푸시
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Casks/my-gemini-app.rb
          git commit -m "fetch: Update my-gemini-app to v${{ env.NEW_VERSION }}"
          git push
