name: Update Homebrew Tap

# "new-release-created" 라는 이름의 신호(dispatch)를 받았을 때만 실행됩니다.
on:
  repository_dispatch:
    types: [new-release-created]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      # 1. 다른 저장소(homebrew-gemini-app)에 접근하기 위해 PAT를 사용해 체크아웃합니다.
      - name: Check out homebrew-gemini-app
        uses: actions/checkout@v4
        with:
          repository: ChoiSeungWoo98/homebrew-gemini-app
          token: ${{ secrets.TAP_REPO_TOKEN }}

      # 2. 커밋을 할 Git 사용자 정보를 설정합니다. (안정성을 위해 추가)
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Homebrew Cask 파일을 자동으로 업데이트합니다.
      - name: Update Homebrew tap
        uses: p-actions/update-homebrew-tap@v1
        with:
          # 업데이트할 Cask 파일의 경로
          formula: Casks/my-gemini-app.rb
          # 앱 저장소 주소 (릴리즈 정보를 가져올 곳)
          repository: ChoiSeungWoo98/gemini_app
          # 커밋 메시지
          commit_message: "feat: Update my-gemini-app to {{version}}"